import { Module } from "@nestjs/common"
import { ConfigModule } from "@nestjs/config"
import { TRPCModule } from "nestjs-trpc"
import { formatTrpcError } from "./error-formatter"
import { AuthMiddleware } from "./middlewares/auth.middleware"
import { DomainErrorMiddleware } from "./middlewares/domain-error.middleware"
import { LoggingMiddleware } from "./middlewares/logging.middleware"
import { PhtMiddleware } from "./middlewares/pht.middleware"
import { RolesMiddleware } from "./middlewares/roles.middleware"
import { ThrottleMiddleware } from "./middlewares/throttle.middleware"
import { TrpcContext } from "./trpc.context"
import { TrpcErrorHandler } from "./trpc-error.handler"

/**
 * tRPC adapter over NestJS (nestjs-trpc). Mounts at /api/trpc alongside the
 * existing REST controllers; both share the same DI container, services, and
 * Better Auth instance. Router types are generated by the Rust CLI into
 * src/trpc/generated/server.ts (committed) and consumed by the web client.
 */
@Module({
  imports: [
    ConfigModule,
    TRPCModule.forRoot({
      basePath: "/api/trpc",
      context: TrpcContext,
      errorFormatter: formatTrpcError,
      onError: TrpcErrorHandler,
      globalMiddlewares: [
        ThrottleMiddleware,
        LoggingMiddleware,
        DomainErrorMiddleware,
        PhtMiddleware,
      ],
    }),
  ],
  providers: [
    TrpcContext,
    TrpcErrorHandler,
    ThrottleMiddleware,
    LoggingMiddleware,
    DomainErrorMiddleware,
    PhtMiddleware,
    RolesMiddleware,
    AuthMiddleware,
  ],
  exports: [AuthMiddleware, RolesMiddleware],
})
export class TrpcModule {}
